/* ============================================================
   人間OS メカニズム辞典 - メカニズムデータ
   ------------------------------------------------------------
   ★ ここに項目を追加するだけで辞典・一手・マップ・検索すべてに反映される。
   ★ id は半角英数 + アンダースコアのみ。一度決めたら変更しない
     （relatedMechanisms / books.js から参照されているため）。
   ★ importance: 'S' | 'A' | 'B' | 'C'
   ★ category: CATEGORIES のキーのいずれか
   ★ relatedMechanisms / books は存在しないIDを書いてもエラーにならない
     （app.js 側で「存在するものだけ」表示する設計）。
============================================================ */

/* ---------------- カテゴリ定義（全15） ---------------- */
const CATEGORIES = {
  survival:  {label:'生存・恒常性',         color:'#a89c87', order:1},
  reward:    {label:'報酬・依存',           color:'#e0ac51', order:2},
  habit:     {label:'習慣・条件付け',       color:'#c79a64', order:3},
  attention: {label:'注意・記憶',           color:'#cdbd8a', order:4},
  judgment:  {label:'判断・意思決定',       color:'#cfa757', order:5},
  bias:      {label:'認知バイアス',         color:'#c4885a', order:6},
  self:      {label:'自己・アイデンティティ', color:'#d8a795', order:7},
  emotion:   {label:'感情・ストレス',       color:'#cf8f6e', order:8},
  defense:   {label:'防衛機制',             color:'#b98f7a', order:9},
  social:    {label:'社会心理・影響力',     color:'#e6cb7c', order:10},
  love:      {label:'恋愛・愛着',           color:'#d68fa1', order:11},
  evolution: {label:'進化心理学',           color:'#bfa97a', order:12},
  motivation:{label:'モチベーション',       color:'#e3c46a', order:13},
  nudge:     {label:'行動変容・ナッジ',     color:'#d2b35c', order:14},
  daimon:    {label:'DAIMON実戦技法',       color:'#f8d77a', order:15},
};

/* ---------------- 重要度定義 ---------------- */
const IMPORTANCE = {
  S: {label:'S', desc:'人生の8割',   color:'#f8d77a'},
  A: {label:'A', desc:'頻出',         color:'#cfa757'},
  B: {label:'B', desc:'知ると強い',   color:'#a99878'},
  C: {label:'C', desc:'専門寄り',     color:'#8a7d68'},
};

/* ---------------- メカニズム本体（現在 S級 42項目） ---------------- */
const MECHANISMS = [

/* ===== 1. 生存・恒常性 ===== */
{
  id:'homeostasis', category:'survival', importance:'S',
  name:'ホメオスタシス', kana:'ほめおすたしす',
  oneLine:'元に戻ろうとする力',
  shortDescription:'体も心も「いつもの状態」に戻ろうとする仕組み。',
  fullDescription:'生命は変化を脅威として扱い、エネルギー消費や心理状態を一定範囲に保とうとする。新しい習慣が数日で崩れるのは意志が弱いからではなく、この調整機能が「元の状態」を正常と判断して引き戻しているから。',
  everydayExample:'禁煙・禁酒・ダイエットを始めても、数日で元の生活パターンに戻ろうとする力が働く。',
  teppeiExample:'早朝に動き出す現場リズムを変えた直後、体が「いつもの時間」に戻ろうとして眠気や違和感が出ることがある。',
  daimonUse:'「戻る一手」はこの引き戻す力を逆向きに使う技法。崩れた状態から"いつもの整った自分"へ戻すスイッチとして設計されている。',
  relatedMechanisms:['reward_system','status_quo_bias','habit_loop','atode_eeyaro'],
  books:['shukan'],
  tags:['習慣','禁煙','禁酒','ダイエット','リバウンド'],
},

/* ===== 2. 報酬・依存 ===== */
{
  id:'reward_system', category:'reward', importance:'S',
  name:'報酬系', kana:'ほうしゅうけい',
  oneLine:'快感をもう一度やりたい',
  shortDescription:'一度感じた快感を、脳がもう一度求めるようになる仕組み。',
  fullDescription:'甘い物・酒・SNS・達成感などで脳内の報酬系が働くと、その行動が「またやりたいこと」として記録される。繰り返すほど回路は強化され、やめにくくなる。',
  everydayExample:'甘い物・SNS・酒・性欲・達成感など、気持ちよかった経験を繰り返したくなる。',
  teppeiExample:'一つの現場をきれいに納めた後の満足感が、次の現場でも同じ精度を求める原動力になっている。',
  daimonUse:'「戻る一手」「証拠回収」は、報酬系を悪い方向ではなく"整った行動"の方へ向け直すための仕組み。',
  relatedMechanisms:['dopamine_prediction','variable_reward','immediate_reward','homeostasis'],
  books:['nokagaku','fuyano'],
  tags:['依存','快感','習慣','モチベーション'],
},
{
  id:'dopamine_prediction', category:'reward', importance:'S',
  name:'ドーパミン予測', kana:'どーぱみんよそく',
  oneLine:'快感そのものより期待で動く',
  shortDescription:'「もらえるかも」という期待が、実際にもらう前から脳を動かす。',
  fullDescription:'ドーパミンは快感そのものではなく「快感が来る予測」で多く分泌される。通知が来た瞬間・当たりそうな瞬間・会えそうな瞬間に、結果より先に反応が起きる。',
  everydayExample:'通知音、当たりそうな相場、会えそうな相手など、結果の前に脳がすでに動いている。',
  teppeiExample:'相場が動き出した瞬間、結果が出る前に「乗りたい」という反応が先に来る。これは予測そのものが快感を作っているサイン。',
  daimonUse:'「一歩引く」は、この予測反応と実際の判断を分けるための一手。反応が来た瞬間に名前を貼ることで、予測に飲まれず本来の判断軸に戻れる。',
  relatedMechanisms:['reward_system','variable_reward','system1','atode_eeyaro'],
  books:['nokagaku','fuyano'],
  tags:['脳科学','期待','通知','相場'],
},
{
  id:'immediate_reward', category:'reward', importance:'S',
  name:'即時報酬', kana:'そくじほうしゅう',
  oneLine:'今すぐ気持ちいい方へ流れる',
  shortDescription:'将来の利益より、今すぐ得られる快感を優先してしまう。',
  fullDescription:'脳は「未来の大きな利益」より「今すぐの小さな快感」を高く評価する傾向がある。長期的に正しい選択でも、今が苦しいと選びにくい。',
  everydayExample:'将来の利益より、今の楽・快感を優先してしまう。',
  teppeiExample:'「今日はもう休みたい」が「明日の段取りを整える」より強く出てくる夜がある。',
  daimonUse:'「明日の一手」は、今すぐ動かなくても"次にやること"だけ先に決めておくことで、即時報酬への流れを弱める。',
  relatedMechanisms:['delay_discounting','reward_system','decision_fatigue','atode_eeyaro'],
  books:['keizai'],
  tags:['行動経済学','先延ばし','意思決定'],
},
{
  id:'delay_discounting', category:'reward', importance:'S',
  name:'遅延割引', kana:'ちえんわりびき',
  oneLine:'未来の価値を小さく見る',
  shortDescription:'時間が先にあるほど、その価値を実際より小さく感じてしまう。',
  fullDescription:'同じ価値でも、手に入るのが未来であるほど割り引いて評価される。健康・資産・信頼など、時間をかけて積み上がるものほど軽視されやすい。',
  everydayExample:'将来の健康より、今の一口・一本の方が強く見える。',
  teppeiExample:'体のメンテナンスや学習投資は、今すぐ結果が出ないぶん優先順位が下がりやすい。',
  daimonUse:'「証拠回収」は、未来の価値を"今日の小さな証拠"に変換して、遅延割引の効果を弱める仕組み。',
  relatedMechanisms:['immediate_reward','self_efficacy','small_win'],
  books:['fast_slow','keizai'],
  tags:['行動経済学','先延ばし','長期思考'],
},
{
  id:'variable_reward', category:'reward', importance:'S',
  name:'変動報酬', kana:'へんどうほうしゅう',
  oneLine:'たまに当たるからハマる',
  shortDescription:'結果が毎回ではなく「たまに」来ると、行動はより強く繰り返される。',
  fullDescription:'一定のご褒美よりも、不規則なご褒美の方が脳を強く刺激する。ギャンブル・SNS通知・相場の急騰など「次は当たるかも」が継続を生む。',
  everydayExample:'ギャンブル、SNS通知、恋愛の不安定な反応に強く引かれる。',
  teppeiExample:'相場で「次のローソク足で動くかも」という感覚は変動報酬そのもの。エントリーの根拠ではなく、この反応で入っていないか一歩引いて見る価値がある。',
  daimonUse:'「後でええやろ」は、変動報酬の"今すぐ確認したい"という反応に対して、確認のタイミングをずらすための一手。',
  relatedMechanisms:['dopamine_prediction','reward_system','heuristic'],
  books:['keizai','fuyano'],
  tags:['ギャンブル','SNS','相場','依存'],
},

/* ===== 3. 習慣・条件付け ===== */
{
  id:'habit_loop', category:'habit', importance:'S',
  name:'習慣ループ', kana:'しゅうかんるーぷ',
  oneLine:'きっかけ→行動→報酬',
  shortDescription:'同じきっかけに対して、同じ行動と報酬が自動で繰り返される回路。',
  fullDescription:'「きっかけ→行動→報酬」のセットが繰り返されると、考えなくても自動的に同じ行動を選ぶようになる。良い習慣も悪い習慣も、同じ仕組みで作られる。',
  everydayExample:'同じ場面で、同じ行動を自動で繰り返してしまう。',
  teppeiExample:'現場に着いて道具を並べる順番が、毎回ほぼ同じ流れになっているのも習慣ループの一つ。',
  daimonUse:'DAIMONの「現場休憩スイッチ」は、このループの中に新しいきっかけと行動を差し込むための仕組み。',
  relatedMechanisms:['trigger','conditioning','environment_design','small_win'],
  books:['shukan'],
  tags:['習慣','ルーティン','自動化'],
},
{
  id:'trigger', category:'habit', importance:'S',
  name:'トリガー', kana:'とりがー',
  oneLine:'行動のスイッチ',
  shortDescription:'特定の場面・時間・感覚が、行動を始めるスイッチになる。',
  fullDescription:'帰宅・風呂前・休憩・寝る前など、特定の状況が「次にこれをする」という行動の引き金になる。トリガーを変えると、行動も変わりやすい。',
  everydayExample:'帰宅、風呂前、休憩、寝る前などで、決まった行動が始まる。',
  teppeiExample:'現場が終わって車に乗った瞬間が、スマホを見るか・今日の振り返りをするかの分岐点になっている。',
  daimonUse:'「現場休憩スイッチ」は休憩というトリガーに、戻る一手という新しい行動を結びつける装置。',
  relatedMechanisms:['habit_loop','conditioning','environment_design'],
  books:['shukan'],
  tags:['習慣','きっかけ','ルーティン'],
},
{
  id:'conditioning', category:'habit', importance:'S',
  name:'条件付け', kana:'じょうけんづけ',
  oneLine:'場面と反応が結びつく',
  shortDescription:'特定の場面と、特定の感情・行動が結びついて自動化される。',
  fullDescription:'ある場面で繰り返し同じ反応をすると、場面そのものがその反応のスイッチになる。コーヒー=休憩、現場終わり=スマホ、のように結びつきは無意識に強化される。',
  everydayExample:'コーヒー=休憩、現場終わり=スマホ、のように場面と行動が結びつく。',
  teppeiExample:'特定の音楽を聞くと集中モードに入る、というのも条件付けの応用。',
  daimonUse:'結びつきは作り直せる。古いスイッチに新しい行動を上書きするのがDAIMONの環境設計の考え方。',
  relatedMechanisms:['trigger','habit_loop','labeling_effect'],
  books:['shukan','nlp'],
  tags:['NLP','習慣','刺激反応'],
},
{
  id:'implementation_intention', category:'habit', importance:'S',
  name:'実行意図', kana:'じっこういと',
  oneLine:'先に「その時やる事」を決める',
  shortDescription:'「もし〜なら、〜する」をあらかじめ決めておくこと。',
  fullDescription:'「もしXが起きたら、Yをする」という形で事前に決めておくと、その場で判断する負荷が減り、実際にYを実行しやすくなる。',
  everydayExample:'もし崩れそうなら、水を飲む / 後でええやろ、と先に決めておく。',
  teppeiExample:'「予定が崩れたら、まず今日の最優先タスク一つだけ決め直す」と決めておくと、現場の変更にも振られにくい。',
  daimonUse:'「一手箱」と「後でええやろ」は、どちらも実行意図の具体形。崩れた時の一手をあらかじめ決めておく仕組み。',
  relatedMechanisms:['small_win','environment_design','self_efficacy','consistency'],
  books:['shukan','ishi'],
  tags:['習慣','行動計画','if-then'],
},
{
  id:'small_win', category:'habit', importance:'S',
  name:'小さな成功', kana:'ちいさなせいこう',
  oneLine:'できた感が次を作る',
  shortDescription:'ごく小さな「できた」が、次の行動への自信とエネルギーを作る。',
  fullDescription:'大きな目標より、すぐ達成できる小さな行動の方が「自分はできる」という感覚を積み上げやすい。この積み上げが次の行動の土台になる。',
  everydayExample:'腕立て1回、明日の一手、戻る一手で再起動する。',
  teppeiExample:'朝のアファメーションを1回だけでも声に出した日は、その後の動き出しが軽くなる。',
  daimonUse:'「証拠回収」はこの小さな成功を記録として残し、自己効力感に変換する仕組み。',
  relatedMechanisms:['self_efficacy','implementation_intention','homeostasis','delay_discounting'],
  books:['shukan'],
  tags:['習慣','自己効力感','再起動'],
},
{
  id:'environment_design', category:'habit', importance:'S',
  name:'環境設計', kana:'かんきょうせっけい',
  oneLine:'環境が行動を決める',
  shortDescription:'意志ではなく、環境の配置で行動を起こりやすく/起こりにくくする。',
  fullDescription:'目に入る場所・手が届く距離・選択肢の数などを変えるだけで、行動の発生率は大きく変わる。意志に頼らない仕組み作りが習慣化の鍵。',
  everydayExample:'見える場所に置く・置かないだけで、行動の頻度が変わる。',
  teppeiExample:'道具を毎回同じ位置に配置しておくと、探す時間が減り、次の動作にすぐ移れる。',
  daimonUse:'「一手箱」は思考を置く場所を一つに決めることで、迷う環境そのものを減らす設計。',
  relatedMechanisms:['habit_loop','trigger','friction_cost','nudge'],
  books:['shukan'],
  tags:['習慣','環境','仕組み化'],
},
{
  id:'friction_cost', category:'habit', importance:'S',
  name:'摩擦コスト', kana:'まさつこすと',
  oneLine:'一手間が行動を止める',
  shortDescription:'行動までの手間が少し増えるだけで、実行率は大きく下がる。',
  fullDescription:'アプリを開く・引き出しを開ける・立ち上がるなど、わずかな手間（摩擦）が行動の有無を左右する。良い行動の摩擦を減らし、避けたい行動の摩擦を増やすのが基本戦略。',
  everydayExample:'一手間増えるだけで、やる気があっても行動が止まる。',
  teppeiExample:'スマホを少し離れた場所に置くだけで、見る回数が自然に減る。',
  daimonUse:'「スマホを置く」「水を飲む」は、摩擦を一段増やすことで反応と行動の間に距離を作る一手。',
  relatedMechanisms:['environment_design','habit_loop','immediate_reward'],
  books:['shukan'],
  tags:['習慣','環境設計','スマホ'],
},

/* ===== 5. 判断・意思決定 ===== */
{
  id:'cognitive_load', category:'judgment', importance:'S',
  name:'認知負荷', kana:'にんちふか',
  oneLine:'頭の容量を使いすぎる',
  shortDescription:'同時に処理する情報が増えるほど、判断の質とスピードが落ちる。',
  fullDescription:'選択・計算・記憶などが重なると、脳のワーキングメモリが圧迫され、ミスや判断の鈍りが増える。容量には限りがある。',
  everydayExample:'選択・音声学習・現場判断が重なると疲れる。',
  teppeiExample:'拾い出しと電話対応と段取り変更が同時に来ると、普段しないミスが出やすくなる。',
  daimonUse:'「明日の一手」は、頭の中の未処理項目を外に出すことで認知負荷そのものを減らす。',
  relatedMechanisms:['decision_fatigue','system2','heuristic','environment_design'],
  books:['fast_slow'],
  tags:['判断','疲労','現場'],
},
{
  id:'decision_fatigue', category:'judgment', importance:'S',
  name:'意思決定疲れ', kana:'いしけっていつかれ',
  oneLine:'選びすぎると判断が鈍る',
  shortDescription:'判断を繰り返すほど、その後の判断の質が下がっていく。',
  fullDescription:'一日の中で行う判断には限りがあり、繰り返すほど「楽な選択」「いつもの選択」に流れやすくなる。疲れた時の判断ほど慎重さが必要。',
  everydayExample:'疲れた夜ほど、食事・スマホ・衝動的な行動に流れやすい。',
  teppeiExample:'現場でいくつも判断した日の夜は、株のエントリー判断も普段より粗くなりやすい。',
  daimonUse:'「後でええやろ」は、疲れた状態での判断を翌日の整った状態に持ち越すための一手。',
  relatedMechanisms:['cognitive_load','immediate_reward','heuristic','self_efficacy'],
  books:['keizai','fast_slow'],
  tags:['判断','疲労','夜'],
},
{
  id:'system1', category:'judgment', importance:'S',
  name:'システム1', kana:'しすてむわん',
  oneLine:'速い直感',
  shortDescription:'ほぼ自動・無意識に動く、速くて省エネな思考モード。',
  fullDescription:'経験に基づき、瞬時にパターンで判断する思考モード。速いが、思い込みやバイアスの影響を強く受ける。',
  everydayExample:'現場の勘で「これは危ない」と瞬時に感じるのはシステム1。',
  teppeiExample:'木目や手触りで「この材は良い」と一瞬で判断できるのは、長年のシステム1が鍛えられている証拠。',
  daimonUse:'システム1の判断は速くて頼りになるが、感情が強い時はシステム2と組み合わせて一歩引く必要がある。',
  relatedMechanisms:['system2','heuristic','dopamine_prediction'],
  books:['fast_slow'],
  tags:['判断','直感','現場の勘'],
},
{
  id:'system2', category:'judgment', importance:'S',
  name:'システム2', kana:'しすてむつー',
  oneLine:'遅い熟考',
  shortDescription:'意識的に注意を使って、ゆっくり正確に考える思考モード。',
  fullDescription:'計算・検証・ルール確認など、時間とエネルギーを使って慎重に進める思考モード。疲労や時間不足で機能しにくくなる。',
  everydayExample:'拾い出しの確認や、相場のルール確認はシステム2の作業。',
  teppeiExample:'「8さんの浅い暴落テク」のルール通りに待てるかどうかは、システム2が機能しているかどうかにかかっている。',
  daimonUse:'「一歩引く」は、システム1の反応にシステム2を割り込ませるための一手。',
  relatedMechanisms:['system1','metacognition','cognitive_load'],
  books:['fast_slow'],
  tags:['判断','熟考','確認'],
},
{
  id:'heuristic', category:'judgment', importance:'S',
  name:'ヒューリスティック', kana:'ひゅーりすてぃっく',
  oneLine:'雑だけど速い近道判断',
  shortDescription:'厳密ではないが、多くの場合うまくいく簡易的な判断のショートカット。',
  fullDescription:'すべてを計算せず、経験則やパターンで素早く結論を出す方法。多くの場面で有効だが、特殊な状況ではズレを生む。',
  everydayExample:'直感で判断する。速いがズレる時もある。',
  teppeiExample:'「この感じならいつも通りでいける」という現場判断は有効だが、初めての条件の時はこの近道を疑う必要がある。',
  daimonUse:'一歩引いて「これはいつものパターンか、違う状況か」を確認することが、ヒューリスティックの誤作動を防ぐ。',
  relatedMechanisms:['system1','variable_reward','decision_fatigue'],
  books:['fast_slow'],
  tags:['判断','直感','近道'],
},

/* ===== 6. 認知バイアス ===== */
{
  id:'loss_aversion', category:'bias', importance:'S',
  name:'損失回避', kana:'そんしつかいひ',
  oneLine:'得より損が痛い',
  shortDescription:'同じ金額でも、得る喜びより失う痛みの方を強く感じる。',
  fullDescription:'心理的なインパクトは、得る場合より失う場合の方が大きいとされる。この差が、損切りや決断の遅れの大きな原因になる。',
  everydayExample:'株・買い物・恋愛で、失う怖さが判断を曲げる。',
  teppeiExample:'ルール通りの見切りラインに来ても「もう少し待てば戻るかも」が出るのは損失回避の典型。ラインを割った時点で判断は出ている。',
  daimonUse:'一歩引いて「これは損失回避が動いてるだけ」と名前を貼ることで、ルール通りの一手に戻りやすくなる。',
  relatedMechanisms:['sunk_cost','endowment_effect','framing','metacognition'],
  books:['keizai','fast_slow'],
  tags:['投資','損切り','行動経済学'],
},
{
  id:'confirmation_bias', category:'bias', importance:'S',
  name:'確証バイアス', kana:'かくしょうばいあす',
  oneLine:'見たい証拠だけ見る',
  shortDescription:'自分の考えに合う情報ばかりを集め、反する情報を軽視してしまう。',
  fullDescription:'一度持った考えや期待に対して、それを支持する情報は目に入りやすく、反対の情報は見落とされやすい。判断の精度を静かに下げる。',
  everydayExample:'自分の考えに合う情報ばかり集めてしまう。',
  teppeiExample:'「上がると思った銘柄」の良いニュースばかり目に入り、悪材料を後回しにしてしまうことがある。',
  daimonUse:'株分析で「確認済み事実」「推測」を分けるルールは、確証バイアスへの直接対策になっている。',
  relatedMechanisms:['anchoring','heuristic','cognitive_dissonance'],
  books:['fast_slow'],
  tags:['投資','判断','バイアス'],
},
{
  id:'status_quo_bias', category:'bias', importance:'S',
  name:'現状維持バイアス', kana:'げんじょういじばいあす',
  oneLine:'今のままを選びやすい',
  shortDescription:'変化のメリットがあっても、変えないことを選びやすい。',
  fullDescription:'変化には不確実性とコストが伴うため、脳は「今のまま」を安全な選択として優先する。これは判断ミスではなく、デフォルトの傾向。',
  everydayExample:'面倒・不安・慣れで、新しい行動を避けてしまう。',
  teppeiExample:'効率の良い新しいやり方を知っていても、現場では慣れた手順を選んでしまうことがある。',
  daimonUse:'「小さな成功」は、現状維持バイアスを越える最小サイズの変化を提供する。',
  relatedMechanisms:['homeostasis','friction_cost','small_win'],
  books:['keizai','fast_slow'],
  tags:['行動経済学','変化','習慣'],
},
{
  id:'anchoring', category:'bias', importance:'S',
  name:'アンカリング', kana:'あんかりんぐ',
  oneLine:'最初の数字に引っ張られる',
  shortDescription:'最初に見た数字や情報が、その後の判断の基準点になってしまう。',
  fullDescription:'一度提示された数値は、その後の評価や交渉の「基準」として無意識に使われる。基準自体が無関係でも影響は残る。',
  everydayExample:'定価20万→10万、と見ると安く感じる。',
  teppeiExample:'「最初に見た株価」が基準になって、その後の上下が割安・割高に見えてしまうことがある。',
  daimonUse:'一歩引いて「この基準はどこから来た？」と確認するだけで、アンカリングの影響をかなり減らせる。',
  relatedMechanisms:['framing','heuristic','loss_aversion','confirmation_bias'],
  books:['fast_slow','keizai'],
  tags:['投資','交渉','判断'],
},
{
  id:'framing', category:'bias', importance:'S',
  name:'フレーミング', kana:'ふれーみんぐ',
  oneLine:'言い方で判断が変わる',
  shortDescription:'同じ内容でも、伝え方や見せ方によって受け取り方が変わる。',
  fullDescription:'「成功率90%」と「失敗率10%」は同じ意味でも印象が異なる。情報の中身ではなく、枠組みが判断を左右する。',
  everydayExample:'90%成功と10%失敗は、印象が変わる。',
  teppeiExample:'同じ作業量でも「あと2割」と「もう8割終わった」では、現場の空気の流れ方が変わる。',
  daimonUse:'自分への語りかけ方を変えるだけで、同じ事実でも受け取り方を整えられる。',
  relatedMechanisms:['anchoring','loss_aversion','self_efficacy'],
  books:['keizai'],
  tags:['伝え方','判断','行動経済学'],
},
{
  id:'sunk_cost', category:'bias', importance:'S',
  name:'サンクコスト', kana:'さんくこすと',
  oneLine:'使った分を捨てられない',
  shortDescription:'すでに使った時間・お金・感情が、今後の判断に影響してしまう。',
  fullDescription:'本来、過去に使ったコストは今の判断材料にならないはずだが、「もったいない」という感覚が継続や撤退の判断を曲げる。',
  everydayExample:'時間・お金・感情を入れるほど、切りにくくなる。',
  teppeiExample:'入った時間が長い案件ほど、見切りの判断が遅れやすい。これは投資の損切りでも同じ構造。',
  daimonUse:'「このコストはもう戻らない」と一歩引いて見るだけで、判断軸を未来側に戻せる。',
  relatedMechanisms:['loss_aversion','endowment_effect','status_quo_bias'],
  books:['keizai'],
  tags:['投資','判断','撤退'],
},
{
  id:'endowment_effect', category:'bias', importance:'S',
  name:'保有効果', kana:'ほゆうこうか',
  oneLine:'持っている物の価値を高く感じる',
  shortDescription:'自分が持っているものは、持っていない時より価値が高く感じられる。',
  fullDescription:'所有しているという事実だけで、その対象への評価が上がる。手放す時に必要以上の損失感を覚えるのはこのため。',
  everydayExample:'持っているものは、同じ物でも高く評価してしまう。',
  teppeiExample:'保有している株は、買う前より好材料に見えやすい。これは銘柄の評価ではなく、保有効果かもしれない。',
  daimonUse:'「これは保有効果かもしれない」と名前を貼るだけで、保有しているという事実と本来の評価を分けて見られる。',
  relatedMechanisms:['loss_aversion','sunk_cost','status_quo_bias'],
  books:['keizai'],
  tags:['投資','所有','評価'],
},
{
  id:'halo_effect', category:'bias', importance:'S',
  name:'ハロー効果', kana:'はろーこうか',
  oneLine:'一つの良い印象が全体に広がる',
  shortDescription:'ある一点が良いと、関係ない部分まで良く見えてしまう。',
  fullDescription:'見た目・話し方・実績など一つの特徴が良いと、その人や物の他の側面まで自動的に高く評価されやすくなる。逆方向（悪い印象が広がる）も同様に働く。',
  everydayExample:'第一印象が良いと、他の部分も良く見えてしまう。',
  teppeiExample:'仕事が丁寧な職人は、提案する他の判断も信頼されやすい。これは実力と同時にハロー効果でもある。',
  daimonUse:'自分自身の整った身なりや所作は、現場での信頼やコミュニケーションにハロー効果として働く。',
  relatedMechanisms:['social_proof','liking','authority'],
  books:['fast_slow'],
  tags:['印象','評価','対人'],
},

/* ===== 7. 自己・アイデンティティ ===== */
{
  id:'self_efficacy', category:'self', importance:'S',
  name:'自己効力感', kana:'じここうりょくかん',
  oneLine:'自分ならできる感',
  shortDescription:'「自分はこれをやり遂げられる」という感覚そのもの。',
  fullDescription:'結果の保証ではなく、過去の小さな成功体験の積み重ねから生まれる感覚。この感覚が強いほど、難しい行動にも取り組みやすくなる。',
  everydayExample:'禁煙・禁酒・早起きの証拠が、次の行動を強くする。',
  teppeiExample:'「今日できた一手」を記録していくことが、次の現場や次のトレードへの自信の土台になる。',
  daimonUse:'「証拠回収」はこの自己効力感を、感覚ではなくデータとして積み上げる仕組み。',
  relatedMechanisms:['small_win','metacognition','implementation_intention','delay_discounting'],
  books:['shukan','adler','ishi'],
  tags:['自信','習慣','証拠'],
},
{
  id:'metacognition', category:'self', importance:'S',
  name:'メタ認知', kana:'めたにんち',
  oneLine:'一歩引いて自分を見る',
  shortDescription:'自分の思考・感情・行動を、外側から観察する視点。',
  fullDescription:'「欲求が来た」と「俺がそうしたい」を分けて見る能力。感情や反応そのものを止めることはできないが、距離を取ることはできる。',
  everydayExample:'欲求=自分、ではなく「欲求が来た」と見る。',
  teppeiExample:'イライラが出た瞬間に「イライラが来た」と気づけると、そのまま行動に出る前に一手選べる。',
  daimonUse:'「一歩引く」のステップそのものがメタ認知の実践。人間OS辞典の核となる動き。',
  relatedMechanisms:['cognitive_dissonance','self_efficacy','system2','labeling_effect'],
  books:['nokagaku','ishi'],
  tags:['観察','自己理解','一歩引く'],
},
{
  id:'cognitive_dissonance', category:'self', importance:'S',
  name:'認知的不協和', kana:'にんちてきふきょうわ',
  oneLine:'矛盾が苦しい',
  shortDescription:'自分の行動と考えが矛盾している時に生じる、不快な感覚。',
  fullDescription:'「良くないと分かっているのにやってしまった」状態は不快感を生み、その不快感を消すために行動か考えのどちらかが（多くは考えの方が）書き換えられる。',
  everydayExample:'悪いと知りつつやると、言い訳でつじつまを合わせる。',
  teppeiExample:'「今日はいいか」と判断を曲げた後、その判断を正当化する理由が後から増えていくことがある。',
  daimonUse:'矛盾そのものに気づいた時点で「後でええやろ」に切り替えると、言い訳作りにエネルギーを使わずに済む。',
  relatedMechanisms:['metacognition','self_efficacy','homeostasis'],
  books:['nlp'],
  tags:['矛盾','言い訳','心理'],
},

/* ===== 10. 社会心理・影響力 ===== */
{
  id:'reciprocity', category:'social', importance:'S',
  name:'返報性', kana:'へんぽうせい',
  oneLine:'もらうと返したくなる',
  shortDescription:'何かを受け取ると、お返しをしたいという気持ちが自然に生まれる。',
  fullDescription:'小さな贈り物や好意でも、受け取った側には「お返しをしないと」という心理的な負債感が生まれる。人間関係の基本的な調整原理の一つ。',
  everydayExample:'現場でコーヒー1本もらうと、関係がスムーズになる。',
  teppeiExample:'ちょっとした差し入れや声かけが、現場の協力関係を滑らかにしているのは返報性の働き。',
  daimonUse:'小さな先出しの好意は、信頼関係の土台づくりに効果的に働く。',
  relatedMechanisms:['liking','consistency','social_proof'],
  books:['eikyo','eigyo'],
  tags:['対人','現場','信頼'],
},
{
  id:'social_proof', category:'social', importance:'S',
  name:'社会的証明', kana:'しゃかいてきしょうめい',
  oneLine:'皆がやると正しく見える',
  shortDescription:'多くの人がしていることは、正しい・安全だと感じやすい。',
  fullDescription:'何が正しいか分からない時、人は他者の行動を判断の基準にする。口コミ・行列・レビューなどが強い影響力を持つのはこのため。',
  everydayExample:'口コミ、行列、レビューで判断が変わる。',
  teppeiExample:'「みんなが買っているから」という情報だけで、エントリーの根拠が薄くなっていないか確認する価値がある。',
  daimonUse:'周りの動きに引っ張られていると感じたら、一度「自分の基準は何だったか」に戻る一手が有効。',
  relatedMechanisms:['mere_exposure','authority','heuristic','halo_effect'],
  books:['eikyo','keizai','eigyo'],
  tags:['投資','口コミ','判断'],
},
{
  id:'scarcity', category:'social', importance:'S',
  name:'希少性', kana:'きしょうせい',
  oneLine:'レアほど欲しくなる',
  shortDescription:'手に入りにくいものほど、価値が高く感じられる。',
  fullDescription:'「限定」「残りわずか」「今だけ」という情報は、対象そのものの価値とは関係なく、欲求を強める。',
  everydayExample:'限定・残りわずか・手に入りにくい相手ほど欲しくなる。',
  teppeiExample:'「今しか買えない」という情報が、判断の質より速さを優先させていないか一歩引いて見る。',
  daimonUse:'「後でええやろ」は、希少性による"今すぐ"の圧力に時間差を作るための一手。',
  relatedMechanisms:['loss_aversion','social_proof','reciprocity','immediate_reward'],
  books:['eikyo','eigyo'],
  tags:['購買','判断','投資'],
},
{
  id:'authority', category:'social', importance:'S',
  name:'権威効果', kana:'けんいこうか',
  oneLine:'肩書きや専門家の言葉を信じやすい',
  shortDescription:'専門家や肩書きのある人の発言は、内容の検証より先に信じられやすい。',
  fullDescription:'「専門家が言っている」という情報自体が、内容の正しさを保証するものとして扱われやすい。情報源の信頼性は内容の検証を省略させる。',
  everydayExample:'専門家・肩書きのある人の言葉は、内容より先に信じられやすい。',
  teppeiExample:'西岡棟梁の言葉が重く響くのは、内容そのものと、積み重ねられた信頼の両方による。',
  daimonUse:'自分自身が「現場で信頼される人」になることは、提案や判断が通りやすくなることにも直結する。',
  relatedMechanisms:['social_proof','halo_effect','liking'],
  books:['eikyo','eigyo'],
  tags:['信頼','対人','現場'],
},
{
  id:'liking', category:'social', importance:'S',
  name:'好意', kana:'こうい',
  oneLine:'好きな人の言うことを受け入れやすい',
  shortDescription:'好意を持っている相手の提案や意見は、内容に関わらず通りやすい。',
  fullDescription:'信頼関係や好意がベースにあると、同じ内容でも受け入れやすさが変わる。関係性そのものがコミュニケーションの土台になる。',
  everydayExample:'好きな相手・気が合う相手の提案は受け入れやすい。',
  teppeiExample:'普段の現場での関係づくりが、急な相談や調整のしやすさに直結している。',
  daimonUse:'日々の小さな信頼の積み重ねが、必要な時の交渉力になる。',
  relatedMechanisms:['reciprocity','mere_exposure','authority'],
  books:['eikyo','eigyo'],
  tags:['対人','信頼','現場'],
},
{
  id:'consistency', category:'social', importance:'S',
  name:'一貫性', kana:'いっかんせい',
  oneLine:'言ったことに合わせたくなる',
  shortDescription:'一度示した態度や発言と、矛盾しない行動を取りたくなる。',
  fullDescription:'自分の発言・選択・約束に対して、後からの行動を一致させたいという心理が働く。小さなコミットメントが、大きな行動を生む土台になる。',
  everydayExample:'一度「やる」と言ったことには、合わせて行動したくなる。',
  teppeiExample:'「明日の一手」を一つでも書いておくと、その通りに動こうとする力が自然に働く。',
  daimonUse:'一手箱・明日の一手は、小さな一貫性の力を翌日の行動につなげる仕組み。',
  relatedMechanisms:['implementation_intention','self_efficacy','reciprocity'],
  books:['eikyo'],
  tags:['対人','行動','コミットメント'],
},
{
  id:'mere_exposure', category:'social', importance:'S',
  name:'単純接触効果', kana:'たんじゅんせっしょくこうか',
  oneLine:'会うほど好感が増える',
  shortDescription:'同じ対象に何度も接するだけで、好感度が上がる。',
  fullDescription:'内容や質に関わらず、繰り返し触れること自体が「安心感」「親しみ」を生む。広告やリピート接触が効果を持つ理由の一つ。',
  everydayExample:'何度も顔を合わせると、安心感と親近感が出る。',
  teppeiExample:'同じ職人と何度も組むうちに、説明なしでも息が合うようになるのは単純接触効果の積み重ね。',
  daimonUse:'毎日のアファメーションや一手の繰り返しも、自分自身への単純接触として、馴染みと安心感を作っていく。',
  relatedMechanisms:['liking','attachment_system','social_proof'],
  books:['danjo','keizai'],
  tags:['対人','習慣','親近感'],
},
{
  id:'labeling_effect', category:'social', importance:'S',
  name:'ラベリング効果', kana:'らべりんぐこうか',
  oneLine:'名前をつけると、その通りになりやすい',
  shortDescription:'何かに名前やレッテルを貼ると、その通りの行動・結果に近づきやすくなる。',
  fullDescription:'自分や他者に貼られたラベルは、その後の行動の指針として機能しやすい。良いラベルも悪いラベルも、同じ仕組みで影響する。',
  everydayExample:'「あなたは○○な人だ」と言われると、その通りに振る舞いやすくなる。',
  teppeiExample:'「精度と速さと美しさで仕事をする大工」というセルフイメージそのものが、日々の判断のラベルとして働いている。',
  daimonUse:'人間OS辞典で反応に名前を貼る行為自体が、ラベリング効果を"観察のため"に使う実践。',
  relatedMechanisms:['conditioning','self_efficacy','metacognition'],
  books:['nlp'],
  tags:['NLP','自己イメージ','言葉'],
},

/* ===== 11. 恋愛・愛着 ===== */
{
  id:'attachment_system', category:'love', importance:'S',
  name:'愛着システム', kana:'あいちゃくしすてむ',
  oneLine:'離れたくない・安心したい',
  shortDescription:'特定の対象との結びつきを保ち、安心を得ようとする心理システム。',
  fullDescription:'恋愛・家族・親密な関係において、距離が離れることへの不安や、近くにいることへの安心感を司る。進化的に生存と結びついた根源的な仕組み。',
  everydayExample:'恋愛、家族、親密な関係で強く出る。',
  teppeiExample:'大切にしている人との関係でこそ、一歩引いて見る視点が一番難しく、一番効果的になる。',
  daimonUse:'愛着システムが強く動いている時こそ「名前を貼る」が冷静さを保つ助けになる。',
  relatedMechanisms:['mere_exposure','reciprocity','belonging_need'],
  books:['evolution_book','danjo'],
  tags:['恋愛','家族','安心'],
},

/* ===== 12. 進化心理学 ===== */
{
  id:'belonging_need', category:'evolution', importance:'S',
  name:'所属欲求', kana:'しょぞくよっきゅう',
  oneLine:'どこかに属していたい',
  shortDescription:'集団やコミュニティの一員でありたいという根源的な欲求。',
  fullDescription:'孤立は進化的に生存リスクと結びついていたため、「どこかに属している」という感覚は安心と直結している。',
  everydayExample:'グループ・チーム・コミュニティに属することで安心感が生まれる。',
  teppeiExample:'現場のチームの中で自分の役割がはっきりしている時ほど、動きに迷いがなくなる。',
  daimonUse:'DAIMONのAIチーム構成（鉄兵＋ゼロ・クロちゃん・Gemini・Manus）も、所属と役割が安心して動ける構造になっている。',
  relatedMechanisms:['status_need','reciprocity','attachment_system'],
  books:['evolution_book','adler'],
  tags:['進化心理学','チーム','安心'],
},
{
  id:'status_need', category:'evolution', importance:'S',
  name:'地位欲求', kana:'ちいよっきゅう',
  oneLine:'認められたい・上に行きたい',
  shortDescription:'集団内での評価や位置づけを上げたいという欲求。',
  fullDescription:'地位の向上は、進化的に資源やパートナーへのアクセスと結びついていた。現代でも、評価・実績・肩書きへの欲求として強く残っている。',
  everydayExample:'評価されたい、認められたい、という欲求が行動を後押しする。',
  teppeiExample:'「速く正確で美しい仕事」が現場での評価につながることは、地位欲求とも自然につながっている。',
  daimonUse:'地位欲求を否定せず、評価される行動の積み重ね（証拠回収）に向けることが、健全な使い方。',
  relatedMechanisms:['belonging_need','social_proof','self_efficacy'],
  books:['evolution_book'],
  tags:['進化心理学','評価','モチベーション'],
},

/* ===== 14. 行動変容・ナッジ ===== */
{
  id:'nudge', category:'nudge', importance:'S',
  name:'ナッジ', kana:'なっじ',
  oneLine:'そっと選択を後押しする',
  shortDescription:'強制せず、選びやすさを変えることで行動を後押しする仕組み。',
  fullDescription:'選択の自由を保ったまま、デフォルトの設定や提示順を変えるだけで、実際に選ばれる行動が変わる。小さな工夫で大きな差が生まれる。',
  everydayExample:'初期設定や見せ方が変わるだけで、選ぶ行動が変わる。',
  teppeiExample:'道具を「使う順番」に並べておくだけで、自然とその順番で作業が進む。',
  daimonUse:'DAIMONのUI設計自体が、欲求を禁止せず「戻る一手」を選びやすくするナッジの集合体。',
  relatedMechanisms:['environment_design','friction_cost','implementation_intention'],
  books:['keizai'],
  tags:['行動経済学','設計','選択'],
},

/* ===== 15. DAIMON実戦技法 ===== */
{
  id:'atode_eeyaro', category:'daimon', importance:'S',
  name:'後でええやろ', kana:'あとでええやろ',
  oneLine:'欲求を許して今だけ遅らせる',
  shortDescription:'欲求を禁止せず、許可した上で「今じゃない」と時間差を作る鉄兵式の核技法。',
  fullDescription:'「やったらアカン」ではなく「今やらなアカン？後でええやろ」と問いかけることで、欲求を否定せずに行動のタイミングだけをずらす。否定しないことで反発が起きにくく、時間が経つと反応そのものが弱まることが多い。',
  everydayExample:'吸ってもええ。でも今吸わなアカン？後でええやろ。',
  teppeiExample:'相場でも現場でも、「今すぐ」が強く来た時に一度「後でええやろ」を挟むだけで、判断の質が変わることが多い。',
  daimonUse:'人間OS辞典・一手モード・DAIMON全体の最深部にある思想。すべての一手の最終ラインとして機能する。',
  relatedMechanisms:['homeostasis','immediate_reward','metacognition','variable_reward'],
  books:['shukan'],
  tags:['DAIMON','鉄兵式','禁煙','禁酒'],
},

];
